---
- name: Change facts if running Windows
  ansible.builtin.set_fact:
    operating_system_tag: "Windows"
    ocp_preference: "windows.2025"
  when: operating_system is match("Win.*")

- name: Change facts if running RHEL9
  ansible.builtin.set_fact:
    ocp_preference: "rhel.9"
  when: operating_system == "RHEL9"

- name: Create and run Linux VM
  redhat.openshift_virtualization.kubevirt_vm:
    state: present
    wait: true
    validate_certs: false
    name: "{{ item }}"
    namespace: openshiftvms
    run_strategy: Always
    labels:
      app: "{{ item }}"
      environment: "{{ env }}"
      operating_system: "{{ operating_system_tag }}"
      owner: "{{ owner.split('@')[0] }}"
      network.kubevirt.io/headlessService: headless
    instancetype:
      name: u1.2xmedium
    preference:
      name: "{{ ocp_preference }}"
    data_volume_templates:
      - metadata:
          name: "{{ item }}"
        spec:
          sourceRef:
            kind: DataSource
            name: "{{ operating_system | lower }}"
            namespace: openshift-virtualization-os-images
          storage:
            resources:
              requests:
                storage: 50Gi
            storageClassName: thin-csi
    spec:
      architecture: amd64
      domain:
        devices:
          disks:
            - bootOrder: 1
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - bridge: {}
              name: externalnetwork
              state: up
            - bridge: {}
              model: virtio
              name: default
        machine:
          type: pc-q35-rhel9.6.0
        resources: {}
      networks:
        - multus:
            networkName: default/ovs-ens35
          name: externalnetwork
        - name: default
          pod: {}
      subdomain: headless
      volumes:
        - dataVolume:
            name: "{{ item }}"
          name: rootdisk
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              disable_root: false
              user: "{{ ocp_user }}"
              password: "{{ ocp_password }}"
              ssh_pwauth: True
              chpasswd:
                list: |
                  root: {{ ocp_password }}
                  {{ ocp_user }}:{{ ocp_password }}
                expire: False
              fqdn: {{ item }}
              hostname: {{ item }}
              runcmd:
                - usermod -p $(echo "{{ ocp_password }}" | openssl passwd -1 -stdin) root
                - usermod -U root
                - sed -i 's/^#\?PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
                - systemctl restart sshd
          name: cloudinitdisk
  loop: "{{ vm_names }}"
  when: operating_system is match("RHEL.*")

- name: Create ConfigMap for unattend.xml
  kubernetes.core.k8s:
    validate_certs: false
    resource_definition:
      apiVersion: v1
      data:
        unattend.xml: |-
          {{ lookup('template', 'templates/unattended.xml.j2') }}
      kind: ConfigMap
      metadata:
        name: sysprep-{{ item }}
        namespace: openshiftvms
    state: present
  loop: "{{ vm_names }}"
  when: operating_system is match("Win.*")

- name: Create and run Windows VM
  redhat.openshift_virtualization.kubevirt_vm:
    state: present
    wait: true
    validate_certs: false
    name: "{{ item }}"
    namespace: openshiftvms
    run_strategy: Always
    labels:
      app: "{{ item }}"
      environment: "{{ env }}"
      operating_system: "{{ operating_system_tag }}"
      owner: "{{ owner.split('@')[0] }}"
      network.kubevirt.io/headlessService: headless
    data_volume_templates:
      - metadata:
          name: "{{ item }}"
        spec:
          sourceRef:
            kind: DataSource
            name: win2k25
            namespace: openshift-virtualization-os-images
          storage:
            resources:
              requests:
                storage: 64Gi
    spec:
      architecture: amd64
      domain:
        clock:
          timer:
            hpet:
              present: false
            hyperv: {}
            pit:
              tickPolicy: delay
            rtc:
              tickPolicy: catchup
          utc: {}
        cpu:
          cores: 1
          sockets: 2
          threads: 1
        devices:
          disks:
            - disk:
                bus: sata
              name: rootdisk
            - cdrom:
                bus: sata
              name: sysprep
          inputs:
            - bus: usb
              name: tablet
              type: tablet
          interfaces:
            - masquerade: {}
              model: virtio
              name: default
            - bridge: {}
              model: virtio
              name: externalnetwork
              state: up
          tpm:
            persistent: true
        features:
          acpi: {}
          apic: {}
          hyperv:
            reenlightenment: {}
            ipi: {}
            synic: {}
            synictimer:
              direct: {}
            spinlocks:
              spinlocks: 8191
            reset: {}
            relaxed: {}
            vpindex: {}
            runtime: {}
            tlbflush: {}
            frequencies: {}
            vapic: {}
          smm: {}
        firmware:
          bootloader:
            efi:
              persistent: true
              secureBoot: true
        machine:
          type: pc-q35-rhel9.6.0
        memory:
          guest: 4Gi
        resources: {}
      networks:
        - name: default
          pod: {}
        - multus:
            networkName: default/ovs-ens35
          name: externalnetwork
      volumes:
        - dataVolume:
            name: "{{ item }}"
          name: rootdisk
        - name: sysprep
          sysprep:
            configMap:
              name: sysprep-{{ item }}
  loop: "{{ vm_names }}"
  when: operating_system is match("Win.*")

- name: Get VMI Info and ensure OS and IP are defined
  redhat.openshift_virtualization.kubevirt_vmi_info:
    validate_certs: false
    name: "{{ item }}"
    namespace: openshiftvms
  register: vmi
  retries: 60
  delay: 10
  until:
    - vmi.resources[0].status.guestOSInfo.prettyName is defined
    - vmi.resources[0].status.interfaces[0].ipAddress is defined
  loop: "{{ vm_names }}"
