---

- name: Move Windows host to workgroup to disable in AD
  microsoft.ad.membership:
    workgroup_name: removegroup
    domain_admin_user: "{{ domainuser }}"
    domain_admin_password: "{{ domainpassword }}"
    state: workgroup
  ignore_errors: true # ignore due to WINRM issues
  when: ansible_host != ip_addr or shadowman_provision_hypervisor|default('RHV') == "OCPV"

- name: Remove Windows host from AD
  when: ansible_host != ip_addr or shadowman_provision_hypervisor|default('RHV') == "OCPV"
  block:
    - name: Delete Windows host from AD
      microsoft.ad.computer:
        name: "{{ fqdn.split('.')[0] }}"
        state: absent
      delegate_to: "dc01.ad.shadowman.dev"
  rescue:
    - name: Retry Delete Windows host from AD due to WINRM
      microsoft.ad.computer:
        name: "{{ fqdn.split('.')[0] }}"
        state: absent
      delegate_to: "dc01.ad.shadowman.dev"

- name: Authenticate to IDM API
  ansible.builtin.uri:
    url: "https://{{ IPA_HOST }}/ipa/session/login_password"
    method: POST
    body_format: form-urlencoded
    headers:
      Referer: "https://{{ IPA_HOST }}/ipa"
      Content-Type: "application/x-www-form-urlencoded"
      Accept: "text/plain"
    body:
      user: "{{ IPA_USER }}"
      password: "{{ IPA_PASS }}"
    status_code: 200
    validate_certs: false # Set to true if using valid CA certs
  register: login
  delegate_to: localhost
  when: shadowman_provision_hypervisor|default('RHV') == "OCPV"

- name: Delete DNS A Record
  ansible.builtin.uri:
    url: "https://{{ IPA_HOST }}/ipa/session/json"
    method: POST
    headers:
      Referer: "https://{{ IPA_HOST }}/ipa"
      Cookie: "{{ login.set_cookie }}"
      Content-Type: "application/json"
      Accept: "application/json"
    body_format: json
    body:
      method: "dnsrecord_del"
      params:
        - ["shadowman.dev", "{{ fqdn.split('.shadowman.dev')[0] }}"]
        - arecord: "{{ ip_addr }}"
      id: 0
    status_code: 200
    validate_certs: false
  delegate_to: localhost
  when: shadowman_provision_hypervisor|default('RHV') == "OCPV"
